trigger:
- master
- development

pool:
  vmImage: 'windows-latest'

variables:
  BuildConfiguration: 'Release'
  MajorVersion: '0'
  MinorVersion: '0'
  Patch: $[counter(format('{0}.{1}.{2}', variables['MajorVersion'], variables['MinorVersion'], variables['Build.SourceBranch']), 5)]
  CurrentVersion: $(MajorVersion).$(MinorVersion).$(Patch)

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(BuildConfiguration)'
    projects: 'CloudOpenDev.Azure.Common.CosmosDB/CloudOpenDev.Azure.Common.CosmosDB.csproj'

- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs: 
    command: 'pack'
    arguments: '--configuration $(BuildConfiguration)'
    projects: 'CloudOpenDev.Azure.Common.CosmosDB/CloudOpenDev.Azure.Common.CosmosDB.csproj'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: CurrentVersion

- task: PublishBuildArtifacts@1
  displayName: 'Publish the nuget packages'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'CloudOpenDev.Azure.Common.CosmosDB'
    publishLocation: 'Container'

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Push NuGet Package To NuGet.org'
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet'

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))
  displayName: 'Push NuGet Package To AzureTestFeed'
  inputs:
    command: 'push'
    searchPatternPush: '$(Build.ArtifactStagingDirectory)/*.nupkg;!$(Build.ArtifactStagingDirectory)/*.Tests.nupkg'
    feedPublish: 'Azure/AzureTestFeed'